# Generated by Django 4.2.13 on 2024-06-11 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_staffprofile_customerprofile_adminprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminprofile',
            options={'verbose_name_plural': 'Admin Profiles'},
        ),
        migrations.AlterModelOptions(
            name='customerprofile',
            options={'verbose_name_plural': 'Customer Profiles'},
        ),
        migrations.AlterModelOptions(
            name='staffprofile',
            options={'verbose_name_plural': 'Staff Profiles'},
        ),
    ]
