# Generated by Django 4.2.13 on 2024-06-11 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_adminprofile_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminProfile',
        ),
    ]
