# Generated by Django 4.2.13 on 2024-06-11 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_adminprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='bio',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='bio',
            field=models.TextField(default='About the user'),
            preserve_default=False,
        ),
    ]
